#! /bin/bash
#
# Setup script for building and testing the project
#
set -eu

sudo apt-get install m4 -y

opam repo add --all -k git github https://github.com/ocaml/opam-repository.git

for switch in $(cat .circleci/opam-switches); do
  echo "Installing dependencies with opam switch $switch"
  opam switch "$switch"
  eval $(opam env)
  opam update
  # Install dependencies as specified in the opam package
  opam install . --deps-only -y
  # Install dependencies needed for tests only
  opam install alcotest
done
