# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v4

    - name: Install build dependencies via homebrew
      run: |
        echo Installing the OCaml toolchain
        brew install gpatch
        brew install ocaml opam
        opam init -y

    - name: Install OCaml dependencies from opam
      run: |
        echo Installing OCaml dependencies
        opam install -y --with-test .

    - name: Run tests
      run: |
        eval $(opam env)
        dune runtest
